[versions]
kotest = "5.5.4"

[libraries]
kotest-assertions-shared = { module = "io.kotest:kotest-assertions-shared", version.ref = "kotest" }
kotest-framework-api = { module = "io.kotest:kotest-framework-api", version.ref = "kotest" }
kotest-runner-juni5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

klock = { module = "com.soywiz.korlibs.klock:klock", version = "3.4.0" }
