name: master

on:
   push:
      paths-ignore:
         - 'doc/**'
         - 'documentation/**'
         - '*.md'
         - '*.yml'
         - '.github/workflows/**'
      branches:
         - master

permissions:
   contents: read

jobs:
   linux:
      runs-on: ubuntu-latest
      strategy:
         fail-fast: false
         matrix:
            target:
               - jvmTest publishJvmPublicationToDeployRepository publishKotlinMultiplatformPublicationToDeployRepository
               - jsTest publishJsPublicationToDeployRepository
               - linuxX64Test publishLinuxX64PublicationToDeployRepository
      steps:
         -  uses: kotest/kotest-action@master
            with:
               gradle-command: ${{ matrix.target }}
               java-version: 11

   mac:
      needs: linux
      runs-on: macos-latest
      strategy:
         fail-fast: false
         matrix:
            target:
               - macosX64Test publishMacosX64PublicationToDeployRepository
               - macosArm64Test publishMacosArm64PublicationToDeployRepository
               - iosX64Test publishIosX64PublicationToDeployRepository
               - iosSimulatorArm64Test publishIosSimulatorArm64PublicationToDeployRepository
               - iosArm64TestKlibrary publishIosArm64PublicationToDeployRepository
               - iosArm32TestKlibrary publishIosArm32PublicationToDeployRepository
               - tvosX64Test publishTvosX64PublicationToDeployRepository
               - tvosArm64TestKlibrary publishTvosArm64PublicationToDeployRepository
               - watchosArm32TestKlibrary publishWatchosArm32PublicationToDeployRepository
               - watchosArm64TestKlibrary publishWatchosArm64PublicationToDeployRepository
               - watchosX86Test publishWatchosX86PublicationToDeployRepository
               - watchosX64Test publishWatchosX64PublicationToDeployRepository
               - watchosSimulatorArm64Test publishWatchosSimulatorArm64PublicationToDeployRepository
               - tvosSimulatorArm64Test publishTvosSimulatorArm64PublicationToDeployRepository
      steps:
         -  uses: kotest/kotest-action@master
            with:
               gradle-command: ${{ matrix.target }}
               java-version: 11

   windows:
      needs: linux
      runs-on: windows-latest
      steps:
         -  uses: kotest/kotest-action@master
            with:
               gradle-command: "mingwX64Test publishMingwX64PublicationToDeployRepository"
               java-version: 11

env:
   OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
   OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
