name: PR-Test

on:
   pull_request:
      paths-ignore:
         - 'doc/**'
         - 'documentation/**'
         - '*.md'
         - '*.yml'
         - '.github/workflows/**'

permissions:
   contents: read

jobs:
   linux:
      runs-on: ubuntu-latest
      strategy:
         fail-fast: false
         matrix:
            target:
               - jvmTest
               - jsTest
               - linuxX64Test
               - linuxArm64TestKlibrary
      steps:
         -  uses: kotest/kotest-action@master
            with:
               gradle-command: ${{ matrix.target }}
               java-version: 17

   mac:
      needs: linux
      runs-on: macos-latest
      strategy:
         fail-fast: false
         matrix:
            target:
               - macosX64Test macosArm64Test
               - iosX64Test iosSimulatorArm64Test iosArm64TestKlibrary iosArm32TestKlibrary
               - tvosX64Test tvosArm64TestKlibrary tvosSimulatorArm64Test
               - watchosArm32TestKlibrary watchosArm64TestKlibrary watchosX86Test watchosX64Test watchosSimulatorArm64Test
      steps:
         -  uses: kotest/kotest-action@master
            with:
               gradle-command: ${{ matrix.target }}
               java-version: 17

   windows:
      needs: linux
      runs-on: windows-latest
      steps:
         -  uses: kotest/kotest-action@master
            with:
               gradle-command: mingwX64Test
               java-version: 17

env:
   GRADLE_OPTS: -Dorg.gradle.configureondemand=false -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxMetaspaceSize=756m -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
