name: release

on:
   workflow_dispatch:
      inputs:
         version:
            description: "The release version"
            required: true
         branch:
            description: "The branch to release from"
            required: true
            default: 'master'


env:
   GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
   RELEASE_VERSION: ${{ github.event.inputs.version }}
   OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
   OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
   ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
   ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

jobs:
   linux:
      runs-on: ubuntu-latest

      steps:
         -  name: Checkout the repo
            uses: actions/checkout@v3
            with:
               fetch-depth: 0
               ref: ${{ github.event.inputs.branch }}

         -  name: Setup JDK
            uses: actions/setup-java@v3
            with:
               java-version: '11'
               distribution: 'temurin'

         -  name: deploy to sonatype
            run: ./gradlew publish

   macos:
      runs-on: macos-latest
      strategy:
         fail-fast: true
         max-parallel: 1
         matrix:
            target:
               - "publishMacosX64PublicationToDeployRepository"
               - "publishMacosArm64PublicationToDeployRepository"
               - "publishIosArm32PublicationToDeployRepository"
               - "publishIosArm64PublicationToDeployRepository"
               - "publishIosX64PublicationToDeployRepository"
               - "publishTvosArm64PublicationToDeployRepository"
               - "publishTvosX64PublicationToDeployRepository"
               - "publishTvosSimulatorArm64PublicationToDeployRepository"
               - "publishWatchosArm32PublicationToDeployRepository"
               - "publishIosSimulatorArm64PublicationToDeployRepository"
               - "publishWatchosArm64PublicationToDeployRepository"
               - "publishWatchosX64PublicationToDeployRepository"
               - "publishWatchosX86PublicationToDeployRepository"
               - "publishWatchosSimulatorArm64PublicationToDeployRepository"
      steps:
         -  name: Checkout the repo
            uses: actions/checkout@v3
            with:
               fetch-depth: 0
               ref: ${{ github.event.inputs.branch }}

         -  name: Setup JDK
            uses: actions/setup-java@v3
            with:
               java-version: '11'
               distribution: 'temurin'

         -  name: deploy to sonatype
            run: ./gradlew ${{ matrix.target }}

   windows:
      runs-on: windows-latest

      steps:
         -  name: Checkout the repo
            uses: actions/checkout@v3
            with:
               fetch-depth: 0
               ref: ${{ github.event.inputs.branch }}

         -  name: Setup JDK
            uses: actions/setup-java@v3
            with:
               java-version: '11'
               distribution: 'temurin'

         -  name: deploy to sonatype
            run: ./gradlew publishMingwX64PublicationToDeployRepository
